---

- hosts: all
  
  vars_files: 
  - ../credentials.yml
  
  tasks:
  - name: Change Password on CISCO IOS
    ios_user:
      name: user
      configured_password: "{{ local_password }}"
      update_password: always
      state: present
    when: ansible_network_os == "ios"
  
  - name: Change Password on CISCO NEXUS OS
    nxos_user:
      name: user
      configured_password: "{{ local_password }}"
      update_password: always
      state: present
      role: priv-15
    when: ansible_network_os == "nxos"
